variables = [
    "NIXPACKS_NO_CACHED_STAGES=1"
]

[node]
version = "20"

[phases.setup]
cmds = ["echo 'using nixpacks for Next.js'"]

[phases.install]
cmds = [
    "npm ci --omit=dev"
]

[phases.build]
cmds = [
    "npm run build"
]

[start]
cmd = "npm run start"
port = 3000
